feat: Update victim status
BuildForSDG/Team-075-ERS pull request #132
Opened 2020-06-16 21:26 UTC by jothamardel

## Description
Victim's status can be updated by response unit.

## Screenshots (if applicable, else remove this line / section)
![Screenshot from 2020-06-16 22-17-32](https://user-images.githubusercontent.com/35902115/84829855-5d5c6600-b020-11ea-8478-d43cc7d27ab9.png)
![Screenshot from 2020-06-16 22-17-40](https://user-images.githubusercontent.com/35902115/84829861-60575680-b020-11ea-898d-5f644e4e5b56.png)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

2020-06-16 22:11 UTC, oluwaseunsamuel submitted a review, later dismissed

2020-06-16 22:58 UTC, jason-ibisi requested changes
Report ID, reporter ID, createdAt, should not be displayed on the modal.

Also fix conflicts.

2020-06-17 05:40 UTC, jothamardel commented
> Report ID, reporter ID, createdAt, should not be displayed on the modal.
> 
> Also fix conflicts.

Resolved conflicts and made changes.

2020-06-17 08:45 UTC, Ose-Me approved these changes

2020-06-17 09:13 UTC, jason-ibisi approved these changes

2020-06-17 09:13 UTC, merged