fix: update-profile css
BuildForSDG/Team-075-ERS pull request #41
Opened 2020-05-22 15:44 UTC by nonsoo24

2020-05-22 16:16 UTC, jothamardel requested changes
- @nonsoo24, this branch has a conflict with the develop branch. I advise you to pull the recent changes made before you start work. 

- Also, let's avoid inline styling and maintain the folder structure we have for every component.

2020-05-22 17:17 UTC, nonsoo24 commented
I pulled before updating this component and I'm not doing any inline styling

2020-05-23 10:23 UTC, Ose-Me approved these changes

2020-05-23 11:38 UTC, jothamardel approved these changes

2020-05-23 11:53 UTC, merged