chore: Live Endpoint
BuildForSDG/Team-075-ERS pull request #49
Opened 2020-05-27 12:05 UTC by jothamardel

## Description
Update front-end to use the live endpoint.

2020-05-27 12:27 UTC, Ose-Me submitted a review, later dismissed

2020-05-27 13:19 UTC, nonsoo24 submitted a review, later dismissed

2020-05-27 19:21 UTC, jason-ibisi requested changes
Please resolve the conflicts

2020-05-28 12:41 UTC, Ose-Me approved these changes

2020-05-28 15:49 UTC, jason-ibisi approved these changes

2020-05-28 15:50 UTC, merged