Ch modal
BuildForSDG/Team-075-ERS pull request #52
Opened 2020-05-27 17:49 UTC by jothamardel

## Description

- Modal reused for feedback, update user profile and victims info 

- Added error handling 

- Redux setup for update profile

2020-05-28 08:53 UTC, nonsoo24 requested changes
Resolve conflict

2020-05-29 07:39 UTC, Ose-Me approved these changes

2020-05-29 07:50 UTC, jason-ibisi approved these changes

2020-05-29 12:15 UTC, nonsoo24 approved these changes

2020-05-29 12:19 UTC, Ose-Me commented
![image](https://user-images.githubusercontent.com/55854888/83258868-f67d2700-a1ae-11ea-9a0d-5afe2ceb03ad.png)

2020-05-29 12:20 UTC, Ose-Me commented
that's how the homepage looks on my screen
and also fix these issues https://app.codacy.com/gh/BuildForSDG/Team-075-ERS/pullRequest?prid=5595115#newIssuesView

2020-05-29 12:46 UTC, Ose-Me commented on src/components/nav-bar/Navbar.jsx
> -import './navbar.css';
you removed the navbar import statement here

2020-05-29 21:59 UTC, jothamardel commented
This branch has bugs but #54 has solved it. Should I go ahead and close this PR? @Ose-Me, @jason-ibisi, @nonsoo24  and @oluwaseunsamuel .

2020-05-29 23:15 UTC, jason-ibisi commented
> This branch has bugs but #54 has solved it. Should I go ahead and close this PR? @Ose-Me, @jason-ibisi, @nonsoo24 and @oluwaseunsamuel .

If #54 has resolved the issues on this branch please close this issue and delete the branch

2020-05-29 23:18 UTC, nonsoo24 approved these changes

2020-05-30 07:08 UTC, closed without merging